// A comprehensive list of Arizona cities for the city filter autocomplete
export const arizonaCities = [
  "Phoenix",
  "Tucson",
  "Mesa",
  "Chandler",
  "Scottsdale",
  "Glendale",
  "Gilbert",
  "Tempe",
  "Peoria",
  "Surprise",
  "Yuma",
  "Avondale",
  "Goodyear",
  "Flagstaff",
  "Buckeye",
  "Casa Grande",
  "Lake Havasu City",
  "Maricopa",
  "Prescott Valley",
  "Prescott",
  "Sierra Vista",
  "Bullhead City",
  "Apache Junction",
  "Queen Creek",
  "Marana",
  "El Mirage",
  "Oro Valley",
  "San Luis",
  "Sahuarita",
  "Kingman",
  "Fountain Hills",
  "Nogales",
  "Douglas",
  "Payson",
  "Paradise Valley",
  "Eloy",
  "Somerton",
  "Cottonwood",
  "Show Low",
  "Sedona",
  "Safford",
  "Camp Verde",
  "Winslow",
  "Coolidge",
  "Globe",
  "Page",
  "Chino Valley",
  "Wickenburg",
  "South Tucson",
  "Tolleson",
  "Snowflake",
  "Bisbee",
  "Florence",
  "Holbrook",
  "Thatcher",
  "Colorado City",
  "Clifton",
  "Willcox",
  "Eagar",
  "Springerville",
  "Miami",
  "Huachuca City",
  "Taylor",
  "Wellton",
  "St. Johns",
  "Kearny",
  "Pinetop-Lakeside",
  "Dewey-Humboldt",
  "Youngtown",
  "Litchfield Park",
  "Guadalupe",
  "Patagonia",
  "Williams",
  "Cave Creek",
  "Superior",
  "Mammoth",
  "Clarkdale",
  "Duncan",
  "Pima",
  "Tombstone",
  "Hayden",
  "Winkelman",
  "Jerome",
  "Fredonia",
  "Star Valley",
  "Parker",
  "Carefree"
]; 